package:
    name: abjad-ipython
    version: 1.0

source:
    path: ../notebooks

requirements:
    run:
        - python >=3.3
        - ipython >=2.3
        - abjad ==2.15

about:
    home: https://github.com/tiagoantao/abjad-ipython
    license: CC 1.0 Universal License

app:
    entry: ipython notebook
    summary: Abjad examples inside IPython Notebook
